-- MySQL Script generated by MySQL Workbench
-- Mon May 13 21:16:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_pizzaria` DEFAULT CHARACTER SET utf8mb4 ;
USE `bd_pizzaria` ;

-- -----------------------------------------------------
-- Table `bd_pizzaria`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pizzaria`.`produtos` (
  `idprodutos` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  `validade` DATE NOT NULL,
  PRIMARY KEY (`idprodutos`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_pizzaria`.`pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_pizzaria`.`pizzas` (
  `idpizzas` INT(11) NOT NULL AUTO_INCREMENT,
  `nomePizza` VARCHAR(45) NOT NULL,
  `produtos_idprodutos` INT(11) NOT NULL,
  PRIMARY KEY (`idpizzas`),
  INDEX `fk_pizzas_produtos_idx` (`produtos_idprodutos` ASC) VISIBLE,
  CONSTRAINT `fk_pizzas_produtos`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `bd_pizzaria`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

USE `bd_pizzaria` ;

-- -----------------------------------------------------
-- function inserirProdutos
-- -----------------------------------------------------

DELIMITER $$
USE `bd_pizzaria`$$
CREATE FUNCTION inserirProdutos() RETURNS INT
BEGIN
-- Molho de tomate
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Molho de tomate', '5 unidades', '2025-06-30');

-- Queijo mozzarella ou muçarela
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Queijo mozzarella', '4kg', '2025-05-15');

-- Pepperoni (salame picante)
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Pepperoni', '2kg', '2025-04-20');

-- Cogumelos
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Cogumelos', '3 caixas', '2025-05-10');

-- Pimentões (verde, vermelho, amarelo)
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Pimentão verde', '1kg', '2025-04-30');
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Pimentão vermelho', '1kg', '2025-04-30');
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Pimentão amarelo', '1kg', '2025-04-30');

-- Cebola
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Cebola', '2kg', '2025-05-05');

-- Azeitonas pretas ou verdes
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Azeitonas pretas', '500g', '2025-05-20');
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Azeitonas verdes', '500g', '2025-05-20');

-- Tomate fresco ou em rodelas
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Tomate', '3kg', '2025-05-25');

-- Presunto
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Presunto', '2kg', '2025-05-10');

-- Bacon
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Bacon', '1kg', '2025-05-15');

-- Salame
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Salame', '1kg', '2025-04-25');

-- Abacaxi (em combinação com presunto, em uma pizza havaiana)
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Abacaxi em calda', '2 latas', '2025-08-31');

-- Linguiça calabresa
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Linguiça calabresa', '1kg', '2025-05-10');

-- Anchovas
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Anchovas', '500g', '2025-04-30');

-- Manjericão fresco
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Manjericão fresco', '3 maços', '2025-05-15');

-- Espinafre
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Espinafre', '1 maço', '2025-05-05');

-- Frango desfiado ou grelhado
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Frango desfiado', '1kg', '2025-05-10');

-- Alho
INSERT INTO produtos (nomeProduto, quantidade, validade) VALUES ('Alho', '500g', '2025-05-20');
    RETURN 1;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
